name: "publish packages"

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/publish.yml'
      - './Itmo.Dev.Editorconfig/Itmo.Dev.Editorconfig.props'
      - './Itmo.Dev.Editorconfig/Itmo.Dev.Editorconfig.csproj'
      - './Itmo.Dev.Editorconfig/.editorconfig'

  workflow_dispatch:

jobs:
  build-and-publish:
    name: build & publish
    runs-on: ubuntu-latest
    environment: nuget.org
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 10.0.x

      - name: restore
        run: dotnet restore Itmo.Dev.Editorconfig.sln

      - name: build
        run: dotnet build Itmo.Dev.Editorconfig.sln -c Release --no-restore /p:PatchVersion=${{ github.run_number }}

      - name: publish to GitHub nuget repository
        run: |
          for file in artifacts/package/release/*.nupkg
          do
            dotnet nuget push "${file#/}" --source "nuget.org" --api-key ${{ secrets.NUGET_API_KEY }}
          done